### ISSUE TITLE
Java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by Luxxii** [MSGFPlus/msgfplus#140]
**Describe the bug**
Hello everyone, currently i am trying to index large peptide fasta files (~50 GB) for peptide searches. This fasta contains 85748938 entries of short peptides (all of them are unique). I am using the SABuild function and call it as follows:

```shell
Xmx256000M -d mouse_mzml_specific_peptides.fasta -tda 1 -decoy XXX
java -Xmx256000M -cp <PATH>/MSGFPLUS_v20220418/MSGFPlus.jar edu.ucsd.msjava.msdbsearch.BuildSA -d mouse_mzml_specific_peptides.fasta -tda 1 -decoy XXX
```

and getting the following Error from MSGF+:
```java
Creating peptides.revCat.fasta.
Building suffix array: /mntc/<PATH>/work/f5/71e50c34429da341c0ad240e4f40ed/peptides.revCat.fasta
Exception in thread "main" java.lang.NegativeArraySizeException: -541141435
        at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.readSequence(CompactFastaSequence.java:542)
        at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:139)
        at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:89)
        at edu.ucsd.msjava.msdbsearch.BuildSA.buildSAFiles(BuildSA.java:144)
        at edu.ucsd.msjava.msdbsearch.BuildSA.buildSA(BuildSA.java:96)
        at edu.ucsd.msjava.msdbsearch.BuildSA.main(BuildSA.java:56)
```

This leads to the following lines [here](https://github.com/MSGFPlus/msgfplus/blob/11b6e2e5a1caac0f429a0bd3bffda6672853abae/src/main/java/edu/ucsd/msjava/msdbsearch/CompactFastaSequence.java#L531-L552). 

I was wondering if this error could be fixed quickly, since i would like to use MSGF+ for identification, even for these large fastas i am using here. Maybe it is only a simple manner of using `long` instead of `int`, because of an possible overflow happening here. But i cannot judge if other places need to be adjusted.

**Comment by Luxxii** [comment]
Thanks for the quick answer! and the clarification! Yes, splitting fasta files are always an option... However, i would look forward to execute a search via a single large fasta file. 

If this is not a priority or not planned, then you can close this issue.
