### ISSUE TITLE
MSGFPlus error message for empty fasta input 

### ISSUE THREAD

**Issue by bernt-matthias** [MSGFPlus/msgfplus#29]
I got the following error (when using MSGFPlus through OpenMS' MSGFPlusAdapter)

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.getByteAt(CompactFastaSequence.java:163)
	at edu.ucsd.msjava.msdbsearch.CompactSuffixArray.createSuffixArrayFiles(CompactSuffixArray.java:280)
	at edu.ucsd.msjava.msdbsearch.CompactSuffixArray.(CompactSuffixArray.java:69)
	at edu.ucsd.msjava.msdbsearch.CompactSuffixArray.(CompactSuffixArray.java:89)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:207)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
```

which seems to be caused by an empty fasta input file. Would it be possible to create a meaningful error message in this case?

**Comment by FarmGeek4Life** [comment]
Note for future reference: the exception reports an error at index 1, so either an empty fasta file, or an error occurred in parsing the fasta file.

**Comment by timosachsenberg** [comment]
Would be great to catch the exception and output a meaningful error message.
