### ISSUE TITLE
msgf_load_database_error

### ISSUE THREAD

**Issue by sjtuyf** [MSGFPlus/msgfplus#30]
I want to use the msgf software to search the protein database.But I meet some error when do the first step.
my script:
java -Xmx80G -jar MSGFPlus.jar -d merge_114_20180428_1.0.fasta -t 10ppm -e 1 -m 3 -inst 1 -ntt 2 -thread 16 -tda 0 -ti 0,1 -n 1 -maxLength 50 -mod Mods.txt -s  vent_merge_30.mgf  -o  vent_merge_30.mgf.mzid

The error information:
java.lang.NegativeArraySizeException
      at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.readSequence(CompactFastaSequence.java:423)
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:98)
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:63)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:226)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:140)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:78)

I do not know what is the reason.Could you help me?Thanks a lot.

Best regards,

**Comment by FarmGeek4Life** [comment]
First of all, please use the latest version of msgf+ before reporting an issue. This issue likely still occurs in the current version, but the line numbers in the error output you provided are no longer accurate, which makes the error significantly harder to investigate.

Are there any empty proteins in the fasta file? This is actually sounding like a problem with the input fasta file.
