### ISSUE TITLE
MSGFPlus NullPointerException

### ISSUE THREAD

**Issue by bernt-matthias** [MSGFPlus/msgfplus#39]
When processing 

https://zenodo.org/record/892005/files/qExactive01819_profile.mzml I get the following error: 

```
Fatal error: Exit code 9 ()
java.lang.NullPointerException
	at edu.ucsd.msjava.msutil.Spectrum.getCharge(Spectrum.java:124)
	at edu.ucsd.msjava.msutil.SpecKey.getSpecKeyList(SpecKey.java:91)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:220)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
```

Any idea what could be wrong. 

Using a protein DB from UniProt with added Decoys (according to the output, reading of the fasta DB seems successful).

**Comment by alchemistmatt** [comment]
The error indicates that the spectrum does not have a precursor ion.  However, we have a bigger problem, and that is that MSGF+ does not support profile mode MSn spectra.  Please re-create your mzML file, but enable centroiding, then try again.  If using msconvert, the command is:
`msconvert.exe DatasetName.raw --mzML --32 --filter "peakPicking true 1-"`
