### ISSUE TITLE
MS-GF+ search in SearchGUI failed

### ISSUE THREAD

**Issue by AnkeTraut** [MSGFPlus/msgfplus#77]
Hello everybody,

I started working with SearchGUI some weeks before. Now I want to use a huge database (82 million entries) for a new project. For the first search I chose only X!Tandem and MS-GF+. After some hours I got first outputs from SearchGUI but only for X!Tandem. Here you can find output of the report:
...
Search progress: 30 / 30 tasks, 100,00% 1,12 hours elapsed
Writing results...
java.lang.NullPointerException
at edu.ucsd.msjava.mzid.MZIdentMLGen.getDBSequence(MZIdentMLGen.java:671)
at edu.ucsd.msjava.mzid.MZIdentMLGen.getPeptideEvidenceList(MZIdentMLGen.java:629)
at edu.ucsd.msjava.mzid.MZIdentMLGen.addSpectrumIdentificationResults(MZIdentMLGen.java:347)
at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:391)
at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)

Fri Sep 20 13:54:59 CEST 2019 MS-GF+ finished for E:\180320_A_01.mgf (2 hours 7248.0 seconds).

Fri Sep 20 13:55:20 CEST 2019 Could not find MS-GF+ result file for 180320_A_01.mgf.
...

the developer of SearchGUI recommend to contact you directly.
Have you any idea what happened? Is my database to big? Or are any other problems possible?

Thanks for helping
Best regards,
Anke

**Comment by FarmGeek4Life** [comment]
Please see issues #13 and #43. The most likely problem is that your database is too big.

**Comment by alchemistmatt** [comment]
FASTA files over ~250 MB in size will need to be split into separate chunks.  You then will search your instrument data against each of the chunks.  Following this, you can use MzidMerger to combine the .mzid files created by the searches
* https://github.com/PNNL-Comp-Mass-Spec/MzidMerger
* https://github.com/PNNL-Comp-Mass-Spec/MzidMerger/releases

If your FASTA file is less than 250 MB, I would guess that MS-GF+ has not been allocated enough memory.  Use the -Xmx switch when calling Java, as described at https://msgfplus.github.io/msgfplus/MSGFPlus.html
For example, this reserves 12 GB of memory
```
java -Xmx120000M  -jar MSGFPlus.jar
```
Does the MS-GF+ search GUI allow you to specify the amount of memory to use?
